version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build using Poetry
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --with=docs
      - sphinx-apidoc -o docs/source/ ./charted
    post_build:
      - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
