theversion: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build using Poetry
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --no-dev
    build:
      - sphinx-build -b html docs/ _build/html
