[tox]
envlist = py310, py311, py312

[testenv]
description = run tests with pytest and measure coverage
deps =
    pytest
    coverage
commands =
    uv run pytest -ra -q
    uv run coverage run -m pytest
    uv run coverage xml

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
basepython = python3
deps =
    sphinx
    sphinx-rtd-theme
commands =
    uv run sphinx-build -b html docs/source docs/build
