name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples or mockups if applicable.
      placeholder: Add code snippets, diagrams, or examples here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
