"""Constants for charted - replaces magic numbers with named constants."""

# Chart dimensions
DEFAULT_CHART_WIDTH = 500
DEFAULT_CHART_HEIGHT = 500

# Typography
DEFAULT_FONT_SIZE = 12
DEFAULT_TITLE_FONT_SIZE = 16
PIE_LABEL_FONT_SIZE = 14
AXIS_LABEL_FONT_SIZE = 12

# Angles (in degrees)
FULL_CIRCLE = 360
RIGHT_ANGLE = 90
STRAIGHT_ANGLE = 180

# Spacing and layout
DEFAULT_PADDING = 18
AXIS_LABEL_ROTATION = 18
MAX_RADIAL_RADIUS_FACTOR = 0.4  # 40% of chart size

# Bar/Column charts
DEFAULT_BAR_GAP = 0.50
DEFAULT_COLUMN_GAP = 0.50

# Axis and reference line styling
AXIS_BORDER_COLOR = "#999"
AXIS_BORDER_WIDTH = 1.5
REFERENCE_LINE_COLOR = "#666"
REFERENCE_LINE_WIDTH = 1.5
REFERENCE_LINE_DASH = "6 3"

# Quadrant label layout
QUADRANT_LABEL_LINE_GAP = 2
QUADRANT_BOTTOM_MARGIN_FACTOR = 0.5
